const locations = [
  "1 Immadihalli",
  "1A Block Koramangala",
  "1Hoysalanagar",
  "1St Block Bel Layout",
  "1St Block Hbr Layout",
  "1St Block Hrbr Layout",
  "1St Block Jayanagar",
  "1St Block Koramangala",
  "1St Phase Jp Nagar",
  "1St Stage Domlur",
  "1St Stage Indira Nagar",
  "2Nd Block Bel Layout",
  "2Nd Block Hrbr Layout",
  "2Nd Block Jayanagar",
  "2Nd Block Koramangala",
  "2Nd Phase Jp Nagar",
  "2Nd Phase Judicial Layout",
  "2Nd Stage Arekere Mico Layout",
  "2Nd Stage Nagarbhavi",
  "3Rd Block Banashankari",
  "3Rd Block Hbr Layout",
  "3Rd Block Hrbr Layout",
  "3Rd Block Jayanagar",
  "3Rd Block Koramangala",
  "3Rd Phase Iti Layout",
  "3Rd Phase Jp Nagar",
  "3Rd Stage Raja Rajeshwari Nagar",
  "4 Bedroom Farm House In Bagalur",
  "4Th Block Jayanagar",
  "4Th Block Koramangala",
  "4Th Phase Jp Nagar",
  "4Th T Block Jayanagar",
  "5Th Block Hbr Layout",
  "5Th Block Jayanagar",
  "5Th Block Koramangala",
  "5Th Phase Jp Nagar",
  "5Th Stage Beml Layout",
  "6Th Block Banashankari 3Rd Stage, 100 Feet Orr",
  "6Th Block Jayanagar",
  "6Th Block Koramangala",
  "6Th Block Rajaji Nagar",
  "6Th Phase Jp Nagar",
  "7Th Block Jayanagar",
  "7Th Phase Jp Nagar",
  "8Th Block Jayanagar",
  "8Th Block Koramangala",
  "8Th Phase Jp Nagar",
  "9Th Block Jayanagar",
  "9Th Phase Jp Nagar",
  "A Narayanapura",
  "Aavalahalli",
  "Abbaiah Reddy Layout",
  "Abbigere",
  "Abshot Layout",
  "Achins Road",
  "Adarsh Nagar",
  "Addischetan Layout",
  "Adityanagar",
  "Adugodi",
  "Aecs Layout",
  "Agara Village",
  "Agb Layout",
  "Agrahara Dasarahalli",
  "Ags Layout",
  "Air View Colony",
  "Aishwarya Crystal Layout",
  "Akash Nagar",
  "Akshaya Nagar",
  "Akshaya Vana",
  "Akshayanagara East",
  "Akshayanagara West",
  "Akshya Nagar",
  "Alfa Garden Layout",
  "Alur",
  "Amam Enclave Layout",
  "Amarjyothi Colony",
  "Ambalipura",
  "Ambedkar Colony",
  "Ambedkar Nagar",
  "Amblipura",
  "Amco Colony",
  "Amrita Nagar",
  "Amruthahalli",
  "Amruthnagar",
  "Ams Layout",
  "Anand Nagar",
  "Anandapura",
  "Anantapura",
  "Anantapuram",
  "Ananth Nagar",
  "Ananthanagar Phase 1,Electronic City , Phase 2",
  "Ananthapura, T C Palaya Main Road",
  "Anathanagar",
  "Andrahalli",
  "Anekal",
  "Anekal - Hosur Road",
  "Anjana Nagar",
  "Anjanapura",
  "Anjappa Layout",
  "Ankappa Layout",
  "Annaiah Reddy Layout",
  "Annapurneshwari Nagar",
  "Annasandrapalya",
  "Anugrah Layout",
  "Anwar Layout",
  "Ardendale",
  "Arehalli",
  "Arekempanahalli",
  "Arekere",
  "Arishinakunte",
  "Ashirvad Colony",
  "Ashok Nagar",
  "Ashraya Layout",
  "Ashwath Nagar",
  "Ashwathnagar",
  "Ashwini Layout",
  "Asthagrama Layout",
  "Atmananda Colony",
  "Attibele",
  "Attur Layout",
  "Austin Town",
  "Avalahalli",
  "Ayappa Nagar",
  "B Channasandra",
  "B K Nagar",
  "B Narayanapura",
  "B Y Raveshwara Nagar",
  "Baba Nagar",
  "Babusapalaya",
  "Badavala Nagar",
  "Badrappa Layout",
  "Bagalakunte",
  "Bagalur",
  "Bagalur Main Road",
  "Bagur",
  "Bagur Road",
  "Bahubali Nagar",
  "Balagere",
  "Balaji Gardens Layout",
  "Banagiri Nagar",
  "Banagirinagar",
  "Banasawadi,",
  "Banashankari",
  "Banashankari 2 Nd Stage",
  "Banashankari 3Rd Stage, Vivekanandanagar",
  "Banashankari 6Th Stage",
  "Banashankari 6Th Stage ,Subramanyapura",
  "Banashankari Stage 2",
  "Banashankari Stage I",
  "Banashankari Stage Ii",
  "Banashankari Stage Iii",
  "Banashankari Stage V",
  "Banashankari Stage Vi",
  "Banashankari3Rd Stage Bigbazar",
  "Banaswadi",
  "Banaswadi,",
  "Bande Nallasandra",
  "Bandepalya",
  "Banjara Layout",
  "Bank Avenue",
  "Bank Of Baroda Colony",
  "Bannerghatta",
  "Bannerghatta Road",
  "Basapura",
  "Basava Nagar",
  "Basavanagara",
  "Basavanapura",
  "Basavangudi",
  "Basavanna Nagar",
  "Basaveshwara Nagar",
  "Basaveshwara Nagar Yelahanka",
  "Basaveswarnagar",
  "Battarahalli",
  "Bcc Layout",
  "Bcmc Layout",
  "Bds Layout",
  "Begur",
  "Begur Road",
  "Behind Don Bosco Church",
  "Bel Layout",
  "Bel Road",
  "Belathur",
  "Belatur",
  "Bellandur",
  "Bellandur,",
  "Bellari Road",
  "Beml Layout",
  "Beml Layout 5Th Stage",
  "Beml Layout, Rajarajeshwari Nagar",
  "Bendiganahalli",
  "Bennigana Halli",
  "Benson Town",
  "Bethel Nagar",
  "Bettahalsoor",
  "Bhagyalakshmi Avenue",
  "Bharat Nagar",
  "Bharath Housing Society Layout",
  "Bharathi Nagar",
  "Bharathnagar",
  "Bhattarahalli",
  "Bhel Layout",
  "Bhoganhalli",
  "Bhoopsandra",
  "Bhuvaneshwari Nagar",
  "Bhuvaneswari Nagar",
  "Bidadi",
  "Bidere Agarahara, Behind Safal Market",
  "Bidrahalli",
  "Bikasipura",
  "Bilal Nagar",
  "Bileshivale",
  "Billamaranahalli",
  "Billapura",
  "Billekahalli",
  "Binnamangala",
  "Binny Mills Employees Colony",
  "Binny Pete",
  "Bisuvanahalli",
  "Bommanahalli",
  "Bommasandra",
  "Bommasandra Industrial Area",
  "Bommenahalli",
  "Brigade Road",
  "Brindavan Layout",
  "Brindavan Nagar",
  "Brooke Bond First Cross",
  "Brookefield",
  "Bsm Extension",
  "Btm 1St Stage",
  "Btm 2Nd Stage",
  "Btm 4Th Stage",
  "Btm Layout",
  "Btm Layout 2Nd Stage 1St Phase",
  "Budigere",
  "Bull Temple Road",
  "Byadarahalli",
  "Byagadadhenahalli",
  "Byappanahalli",
  "Byatarayanapura",
  "Byrasandra",
  "Byrasandra Extension",
  "Byrathi Village",
  "Cambridge  Road",
  "Cambridge Layout",
  "Canara Bank Colony",
  "Canara Bank Layout",
  "Carmelaram",
  "Celebrity Paradise Layout",
  "Chaitanya Ananya",
  "Challaghatta",
  "Chambenahalli",
  "Chamrajpet",
  "Chamundi Nagar",
  "Chandapura",
  "Chandra Layout",
  "Channasandra",
  "Channasandra Layout",
  "Chelekare",
  "Chellikere",
  "Chennammana Kere",
  "Chennammanakere Achukattu",
  "Chennappa Layout",
  "Chikbasavanapura",
  "Chikka Banaswadi",
  "Chikka Tirupathi",
  "Chikkaballapur",
  "Chikkabanavar",
  "Chikkabidarakallu",
  "Chikkadunnasandra",
  "Chikkagubbi",
  "Chikkajala",
  "Chikkakannalli",
  "Chikkalasandra",
  "Chikkanahalli",
  "Chikkasandra",
  "Chikkathoguru",
  "Chikkatirupathi",
  "Chikku Lakshmaiah Layout",
  "Chinnapanahalli",
  "Chokkahalli",
  "Chokkanahalli",
  "Chokkasandra",
  "Cholanayakanahalli",
  "Choodasandra",
  "Chowdeshwari Layout",
  "Chuchangatta Colony",
  "Church Street",
  "Ckikkakammana Halli",
  "Classic Paradise Layout",
  "Cleveland Town",
  "Cmh Road",
  "Coconut Garden",
  "Coconut Grove Layout",
  "Coffee Board Layout",
  "Cooke Town",
  "Cottonpet",
  "Cox Town",
  "Cqal Layout",
  "Cqal Layout C Block",
  "Cr Layout",
  "Craig Park Layout",
  "Crimson Layout",
  "Cubbon Road",
  "Cunningham Road",
  "Cv Raman Nagar",
  "D Group Employees Layout",
  "D Souza Layout",
  "Daadys Gaarden Layout",
  "Dairy Circle",
  "Dasanapura",
  "Dasappa Layout",
  "Dasarahalli",
  "Deepanjali Nagar",
  "Defence Colony",
  "Defence Layout",
  "Dena Bank Colony",
  "Devanahalli",
  "Devanahalli Int. Airport",
  "Devanahalli Road",
  "Devara Jeevanahalli",
  "Devarabeesana Halli",
  "Devarabisanahalli",
  "Devarachikkanahalli",
  "Devasandra Extension",
  "Devasthanagalu",
  "Devi Nagar",
  "Dinnur",
  "Divya Unnathi Layout",
  "Doctor Layout Rayasandra",
  "Doctors Layout",
  "Dodda Banaswadi",
  "Dodda Kempaiah Layout",
  "Dodda Nekkundi",
  "Dodda Nekkundi Extension",
  "Doddaballapur",
  "Doddabanahalli",
  "Doddabele",
  "Doddabidrakallu",
  "Doddabommasandra",
  "Doddagubbi",
  "Doddakallasandra",
  "Doddakammanahalli",
  "Doddakannelli",
  "Doddanakundi Industrial Area 2",
  "Doddanakunte",
  "Doddanekundi",
  "Doddathoguru",
  "Dodsworth Layout",
  "Dollar Scheme Colony",
  "Dollars Colony",
  "Dollars Layout",
  "Dominic Layout",
  "Domlur",
  "Domlur Layout",
  "Dommasandra",
  "Doopanahalli",
  "Dooravani Nagar",
  "Dr Shivarama Karantha Nagar",
  "Duddanahalli",
  "Duo Layout",
  "Duvasapalya",
  "Dwaraka Nagar",
  "Dwarka Nagar",
  "Ecc Road, Whitefield,",
  "Ejipura",
  "Electronic City",
  "Electronic City Phase 1,",
  "Electronic City Phase Ii",
  "Electronics City Phase 1",
  "Epip Area, Whitefield",
  "Epip Zone",
  "Escorts Colony",
  "Esther Enclave Layout",
  "Ferrar Nagar",
  "Frazer Town",
  "Friends Colony",
  "Gandhi Bazar",
  "Ganesha Block",
  "Ganga Nagar",
  "Ganga Nagar Extension",
  "Garden Layout",
  "Garebhavipalya",
  "Garudachar Palya",
  "Gattahalli",
  "Gattigere",
  "Gaundanapalya",
  "Gaurava Nagar",
  "Gayathri Nagar",
  "Gb Palya",
  "Gd Layout",
  "Geddalahalli",
  "Geetanjali Layout",
  "Geleyara Balaga Layout",
  "Gidada Konnenahalli",
  "Giri Nagar",
  "Gkvk Layout",
  "Gkw Layout",
  "Glass Factory Layout",
  "Gm Palaya",
  "Gnana Bharathi",
  "Gokaula Extension",
  "Gokula Extension",
  "Gollahalli",
  "Gollarapalya Hosahalli",
  "Gopal Reddy Layout",
  "Gopalapura",
  "Gopalkrishna Nagar",
  "Goraguntepalya",
  "Gottigere",
  "Govindapura",
  "Govindaraja Nagar Ward",
  "Govindpura",
  "Govindraja Nagar",
  "Gowdanapalya",
  "Green Domain Layout",
  "Green Garden Layout",
  "Green Glen Layout",
  "Green View Layout",
  "Green Woods Layout",
  "Gubbalala",
  "Gubbi Cross, Hennur Main Road",
  "Guddadahalli",
  "Gulakamale",
  "Gulimangala",
  "Guni Agrahara",
  "Gunjur",
  "Gunjur Palya",
  "Hadosiddapura",
  "Hagadur",
  "Hal 2Nd Stage",
  "Hal 3Rd Stage",
  "Hal Layout",
  "Hal Old Airport Road",
  "Halanayakanahalli",
  "Hallehalli",
  "Handenahalli",
  "Hanumagiri",
  "Hanuman Nagar",
  "Hanumanth Nagar",
  "Hanumantha Nagar",
  "Haralur Road",
  "Haralur Road,",
  "Harappanahalli",
  "Harlur",
  "Harohalli",
  "Harsha Layout",
  "Havanur Extension",
  "Hbr Layout",
  "Hebbal",
  "Hebbal Kempapura",
  "Hegde Nagar",
  "Hegganahalli",
  "Hennagara",
  "Hennur",
  "Hennur Bande",
  "Hennur Busstop",
  "Hennur Gardens",
  "Hennur Road",
  "Herohalli",
  "Hessarghatta",
  "High Grounds",
  "Himagiri Meadows",
  "Hiremath Layout",
  "Hmt Layout",
  "Hommadevanahalli",
  "Hongasandra",
  "Hoodi",
  "Hoodi Circle,",
  "Hoodi Layout",
  "Horamavu Agara",
  "Horamavu Banaswadi",
  "Hormavu",
  "Hosa Road",
  "Hosahalli",
  "Hosahalli Extension",
  "Hosakerehalli",
  "Hosakerehalli Layout",
  "Hosapalya",
  "Hoskote",
  "Hoskote Near",
  "Hosur Main Road",
  "Hosur Rmain Road",
  "Hosur Road",
  "Howthinarayanappa Garden",
  "Hoysalanagar",
  "Hrbr Layout",
  "Hsr Layout",
  "Hsr Layout 7Th Sector,",
  "Hsr Layout Sector3",
  "Hulimavu",
  "Hunasamaranahalli",
  "Huskur",
  "Huttanahalli",
  "Iblur Village",
  "Iggalur",
  "Immadihalli",
  "Indira Nagar",
  "Indira Nagar 3Rd Stage",
  "Indira Nagar Stage 2",
  "Indiranagar Hal 2Nd Stage",
  "Indra Nagar",
  "Indranagar  100Ft Road Defence Colony",
  "Infantry Road",
  "Isro Layout",
  "Iti Employees Layout",
  "Iti Layout",
  "Itpl",
  "Ittamadu",
  "J C Nagar",
  "J P Nagar 7Th Phase Ramayya City",
  "J.P.Nagar 6Th Phase.Sarakki Nagar",
  "Jagadish Nagar",
  "Jagajyothi Layout",
  "Jai Bheema Nagar",
  "Jakkasandra",
  "Jakkasandra Extension",
  "Jakkur",
  "Jakkur Plantation",
  "Jakkuru Layout",
  "Jakkuryelahanka",
  "Jaladarsini Layout",
  "Jalahalli",
  "Jalahalli East",
  "Jalahalli West",
  "Janatha Colony",
  "Javarandoddi",
  "Jaya Mahal Layout",
  "Jaya Nagar East",
  "Jayamahal",
  "Jayamahal Extension",
  "Jayanagar",
  "Jayanagar,",
  "Jayanti Nagar",
  "Jaymahal Road",
  "Jcr Layout",
  "Jeevan Bima Nagar",
  "Jeevanhalli",
  "Jigani",
  "Jinkethimmanahalli",
  "Jnana Ganga Nagar",
  "Jnanabharathi Layout",
  "Jogupalya",
  "Jp Nagar",
  "Jp Nagar 7Th Phase,",
  "Jp Nagar 8Th Phase .",
  "Jp Nagar 8Th Phase,",
  "Jp Nagar 9Th Phase,",
  "Judicial Layout",
  "Judicial Layout, Kanakapura Road,",
  "Junnasandra",
  "Jyothi Nagar",
  "K G Colony",
  "K R C Kothanur",
  "Kachanayakanahalli",
  "Kacharakanahalli",
  "Kada Agrahara",
  "Kadabagere",
  "Kadarenahalli",
  "Kadubeesanahalli",
  "Kadugodi",
  "Kadugondanahalli",
  "Kaggadasapura",
  "Kaggalipura",
  "Kaikondrahalli",
  "Kalena Agrahara",
  "Kalhalli",
  "Kalkere",
  "Kalkere Channasandra",
  "Kallumantapa",
  "Kalyan Nagar",
  "Kamakiya",
  "Kamakshipalya",
  "Kamakya Layout",
  "Kamala Nagar",
  "Kambipura",
  "Kamdhenu Nagar",
  "Kammagondahalli",
  "Kammanahalli",
  "Kammasandra",
  "Kanaka Nagar",
  "Kanakadasa Layout",
  "Kanakapur Main Road",
  "Kanakapura",
  "Kanakapura  Rod",
  "Kanakapura Main  Road",
  "Kanakapura Road,",
  "Kanakpura Road",
  "Kannamangala",
  "Kannur",
  "Kariyammana Agrahara",
  "Karnataka Shabarimala",
  "Karuna Nagar",
  "Kasavanhalli",
  "Kashi Nagar",
  "Kasthuri Nagar East Of Ngef",
  "Kasturi Nagar",
  "Kathreguppe",
  "Kathriguppe",
  "Kathriguppe Iv Phase",
  "Kattigenahalli",
  "Kaval Byrasandra",
  "Kaverappa Layout",
  "Kaveri Nagar",
  "Kavika Layout",
  "Keb Colony",
  "Keerthi Layout",
  "Kempapura",
  "Kempegowda Nagar",
  "Kenchanehalli R R Nagar",
  "Kenchenahalli",
  "Kenchenhalli",
  "Kengeri",
  "Kengeri Hobli",
  "Kengeri Satellite Town",
  "Kengeri Satellite Town ( Bda Site)",
  "Kengeri Satellite Town Khb Apartment",
  "Kengeri Satellite Town Stage Ii",
  "Kereguddadahalli",
  "Keshava Nagar",
  "Kg Halli",
  "Khb Colony Extension",
  "Kirloskar Layout",
  "Kirloskar Layout, Basaveshwarnagar",
  "Kithaganur",
  "Kodanda Reddy Layout",
  "Kodathi",
  "Kodbisanhalli",
  "Kodichikkanahalli",
  "Kodigehaali",
  "Kodigehalli",
  "Kodihalli",
  "Kodipalya",
  "Kogilu",
  "Konanakunte",
  "Konanakunte Cross",
  "Konappana Agrahara",
  "Konena Agrahara",
  "Koppa",
  "Koramangala",
  "Koramangala Industrial Layout",
  "Kothannur",
  "Kothanur",
  "Kothnoor Dinne",
  "Kothnur Narayanapura",
  "Kpc Layout",
  "Kr Garden",
  "Kr Layout",
  "Kr Puram",
  "Krishna Nagar",
  "Krishna Reddy Layout",
  "Ksrtc Layout",
  "Kudlu",
  "Kudlu Gate",
  "Kudlu Main Road",
  "Kudlu Village,",
  "Kullappa Colony",
  "Kumara Park",
  "Kumarapalli",
  "Kumaraswami Layout",
  "Kumbalgodu",
  "Kumbena Agrahara",
  "Kundalahalli",
  "Kundalahalli Colony",
  "Kurubarahalli",
  "Kuvempu Layout",
  "Kuvempu Nagar",
  "Kyalasanahalli",
  "Laggere",
  "Lake City",
  "Lakkasandra",
  "Lakshmi Layout",
  "Lakshmiamma Garden",
  "Lakshminarayana Pura",
  "Lakshminarayanapura, Electronic City Phase 2",
  "Lakshmipura",
  "Lakshmipura Vidyaanyapura",
  "Lal Bahadur Shastri Nagar",
  "Lalbagh Road",
  "Langford Gardens",
  "Langford Town",
  "Lavakusha Nagar",
  "Lavelle Road",
  "Laxmi Sagar Layout",
  "Laxminarayana Layout",
  "Lb Shastri Nagar",
  "Lic Colony",
  "Lingadheeranahalli",
  "Lingarajapuram",
  "Lottegolla Halli",
  "M C Layout",
  "M.G Road",
  "Madanayakahalli",
  "Madavara",
  "Madiwala",
  "Magadi Road",
  "Mahadevpura",
  "Mahaganapathy Nagar",
  "Mahalakshmi Layout",
  "Mahalakshmi Puram",
  "Maheswari Nagar",
  "Mailasandra",
  "Maithri Layout",
  "Makali",
  "Malimakanapura",
  "Mallappa Layout",
  "Mallasandra",
  "Mallathahalli",
  "Malleshpalya",
  "Malleshwaram",
  "Malur Hosur Road",
  "Manayata Tech Park",
  "Mangammanapalya",
  "Mango Garden Layout",
  "Manjunath Nagar",
  "Manjunatha Layout",
  "Manorayana Palya",
  "Maragondana Halli, Kr Puram, Old Madras Road",
  "Maragondanahalli",
  "Marasandra",
  "Marathahalli",
  "Marathalli Bridge",
  "Marenahalli",
  "Margondanahalli",
  "Mariyannapalya",
  "Marsur",
  "Maruthi Extension",
  "Maruthi Hbcs Layout",
  "Maruthi Layout",
  "Maruthi Nagar",
  "Maruthi Nagar Kogilu",
  "Maruthi Sevanagar",
  "Mathikere",
  "Mathikere Extension",
  "Mathikere Sbm Colony",
  "Mcechs  Layout",
  "Medahalli",
  "Medaralli",
  "Medi Agrahara",
  "Meenakunte",
  "Mei Layout, Bagalgunte",
  "Michael Palaya",
  "Mico Layout",
  "Milk Colony",
  "Millers Road",
  "Mla Layout",
  "Moodalapalya",
  "Motappa Layout",
  "Mrcr Layout",
  "Ms Pallya",
  "Mukkutam Nagar",
  "Mullur",
  "Muneshwara Nagar",
  "Munivenkatppa Layout",
  "Munnekollal",
  "Murugeshpalya",
  "Muthurayya Swamy Layout",
  "Muthyala Nagar",
  "Mylasandra",
  "Mysore Highway",
  "Mysore Road",
  "Nagadevanahalli",
  "Naganathapura",
  "Nagappa Reddy Layout",
  "Nagaraja Garden",
  "Nagarbhavi",
  "Nagarbhavi Garden Villas Layout",
  "Nagasandra",
  "Nagashetty Halli",
  "Nagavara",
  "Nagavarapalya",
  "Nagawara Junction",
  "Nagondanahalli",
  "Naidu Layout",
  "Nallurhalli",
  "Nandi Durga Road",
  "Nandi Hills",
  "Nandini Layout",
  "Nanjappa Garden",
  "Nanjappa Layout",
  "Narayana Nagar 1St Block",
  "Narayanappa Garden",
  "Narayanapura",
  "Nayandanahalli",
  "Ncpr Industrial Layout",
  "Near Electronic City,",
  "Near International Airport",
  "Near Ramanashree California Resort",
  "Near Ullas Theater",
  "Neeladri Nagar",
  "Neelamangala",
  "Nehru Nagar",
  "Nelamangala",
  "New Gurappana Palya",
  "New Thippasandra",
  "Ngef Layout",
  "Ngr Layout",
  "Nobo Nagar",
  "Nr Colony",
  "Nri Layout",
  "Ns Palya",
  "Nti Layout",
  "Nyanappana Halli",
  "Off Bannergatta Road",
  "Off Sarjapur Road,",
  "Old Airport Road",
  "Old Gurappanapalya",
  "Old Madras Road",
  "Old Mangammanapalya Road",
  "Omarbagh Layout",
  "Ombr Layout",
  "Omkar Nagar",
  "Other",
  "Outer Ring Road East",
  "P Krishnappa Layout",
  "P&T Colony",
  "P&T Layout",
  "Padmanabhanagar",
  "Pai Layout",
  "Pai Layout , Mahadevapura",
  "Palace Guttahalli",
  "Palace Road",
  "Palanahalli",
  "Pampa Extension",
  "Panathur",
  "Panathur Road,",
  "Panduranga Nagar",
  "Papareddipalya",
  "Parappana Agrahara",
  "Patelappa Layout",
  "Pattanagere",
  "Pattandur Agrahara",
  "Pc Palaya",
  "Peenya",
  "Phase 1 Kammasandra",
  "Pillahalli",
  "Pns Layout",
  "Poorna Pragna Layout",
  "Poornapragna Housing Society Layout",
  "Popular Colony",
  "Postal Colony",
  "Pragathi Nagar",
  "Prakash Nagar",
  "Prakruthi Nagar",
  "Prasanna Layout Herohalli",
  "Prasanth Extension",
  "Prasanti Nagar",
  "Prashanth Nagar",
  "Prestige Sunrise",
  "Prithvi Layout",
  "Pulikeshi Nagar",
  "Pulkeshi Nagar",
  "Punappa Layout",
  "Puttanahalli",
  "Puttappa Layout",
  "Queens Road",
  "R.T. Nagar",
  "Race Course Road",
  "Rachenahalli",
  "Raghavendra Layout",
  "Raghavendra Nagar",
  "Raghuvanahalli",
  "Rahat Bagh",
  "Rahmath Nagar",
  "Rainbow Drive",
  "Raja Rajashweri Nagar",
  "Raja Rajeshwari Nagar",
  "Raja Rajeshwari Nagar 5Th Stage",
  "Raja Rajeshwari Nagara",
  "Rajaji Nagar",
  "Rajankunte",
  "Rajanna Layout",
  "Rajapura",
  "Rajarajesheari Nagar",
  "Rajarajeshwari Nagar",
  "Rajarajeshwari Nagara",
  "Rajarajeshwarinagar",
  "Rajasree Layout",
  "Rajiv Gandhi Nagar",
  "Rajiv Nagar",
  "Ramagondanahalli",
  "Ramakrishnappa Layout",
  "Ramamohanapuram",
  "Ramamurthy Nagar",
  "Ramamurthy Nagar Extension",
  "Ramanagara Channapatna",
  "Ramanashree Enclave",
  "Ramanjaneyanagar",
  "Ramaswamy Palya - Kammanahalli Main Road",
  "Ramchandrapuram",
  "Ramesh Nagar",
  "Rammana Layout",
  "Ravindra Nagar, T.Dasarahalli Peenya",
  "Rayasandra",
  "Rbi Layout",
  "Reliaable Tranquil Layout",
  "Reliable Woods Layout",
  "Remco Bhel Layout",
  "Rest House Road",
  "Richards Town",
  "Richmond Road",
  "Richmond Town",
  "Ring Road Nagarbhavi",
  "Rk Layout 2Nd Stage",
  "Rmv",
  "Rmv 2Nd Stage",
  "Rmv Extension",
  "Rmv Extension Stage 2",
  "Rmv Extension Stage 2, Rmv Extension",
  "Roopena Agrahara",
  "Rpc Layout",
  "Rr Layout",
  "Rto Ullalu",
  "Rukmaiah Layout",
  "Rustam Bagh Layout",
  "Rwf West Colony",
  "S R Layout",
  "Sabari Nagar",
  "Sadahalli",
  "Sadanand Nagar",
  "Sadaramangala",
  "Sadashiva Nagar",
  "Sadduguntepalya",
  "Sadhguru Layout",
  "Sahakara Nagar",
  "Sahyadri Layout",
  "Sai Gardens",
  "Samethanahalli",
  "Sampangi Rama Nagar",
  "Sampangirama Nagar",
  "Sampige Layout",
  "Sampigehalli",
  "Sanjay Nagar",
  "Sanjeevini Nagar",
  "Sanne Amanikere",
  "Saptagiri Layout",
  "Sapthagiri Layout",
  "Sarakki Nagar",
  "Sarjapur",
  "Sarjapur  Road",
  "Sarjapur Bagalur Road",
  "Sarjapur Road,",
  "Sarjapura - Attibele Road",
  "Sarvabhouma Nagar",
  "Sarvobhogam Nagar",
  "Sathanur",
  "Sathya Layout",
  "Sathya Sai Layout",
  "Satyasaibaba Layout",
  "Sbm Colony",
  "Sector 1 Hsr Layout",
  "Sector 2 Hsr Layout",
  "Sector 4 Hsr Layout",
  "Sector 6 Hsr Layout",
  "Sector 7 Hsr Layout",
  "Seegehalli",
  "Seethappa Layout",
  "Seetharampalya",
  "Seshadripuram",
  "Shakthi Nagar",
  "Shampura",
  "Shankarapuram",
  "Shanthala Nagar",
  "Shanthi Layout",
  "Shanthi Pura",
  "Shanthinagar",
  "Shanti Nagar",
  "Shantiniketan Layout",
  "Shauhardha Layout",
  "Shettigere",
  "Shettihalli",
  "Shetty Halli",
  "Shikaripalya",
  "Shingapura",
  "Shirdi Sai Layout",
  "Shirdi Sai Nagar",
  "Shivaji Nagar",
  "Shree Ananth Nagar Layout",
  "Siddapura",
  "Sidedahalli",
  "Silk Board",
  "Silver Springs Layout",
  "Sindhi Colony",
  "Singanayakanahalli",
  "Singapura Village",
  "Singasandra",
  "Singena Agrahara",
  "Sir M V Nagar",
  "Sk Garden",
  "Smv Layout",
  "Sneha Colony",
  "Somanna Garden",
  "Somasundara Palya",
  "Someshwara Layout",
  "Sompura",
  "Sonam Layout",
  "Sonnenahalli",
  "Soppahalli",
  "Soundarya Layout",
  "South",
  "Sree Narayana Nagar",
  "Sri Balaji Krupa Layout",
  "Sri Kanteshwara Nagar",
  "Sri Sai Layout",
  "Sri Venkateshpura Layout",
  "Srigandada Kaval",
  "Srinagar",
  "Srinivas Colony",
  "Srinivasa Nagar",
  "Srinivasapura",
  "Srirampura",
  "Srirampuram",
  "St Thomas Town",
  "St. John'S Road",
  "Stage-4 Bommanahalli",
  "Subash Nagar",
  "Subbannaiah Palya",
  "Subhash Nagar",
  "Subramanya Nagar",
  "Subramanyapura",
  "Suddaguntepalya",
  "Sugama Layout",
  "Sultan Palaya",
  "Sulthangunta",
  "Sundar Ram Shetty Nagar",
  "Sundara Nagar",
  "Sunder Ram Shetty Nagar",
  "Sunkadakatte",
  "Sunkan Palya",
  "Surabhi Layout",
  "Suragajakkanahalli",
  "Suraksha Nagar",
  "Suryanagar",
  "Syndicate Bank Colony",
  "T C Palya",
  "T C Palya Main Road",
  "T Dasarahalli",
  "T G Extension",
  "T K Reddy Layout",
  "T R Mill Road",
  "T.C Palya",
  "Tala Cauvery Layout",
  "Talaghattapura",
  "Tasker Town",
  "Tata Nagar",
  "Tavarekere",
  "Tc Palaya",
  "Teachers Colony",
  "Tejaswini Nagar",
  "Telecom Layout",
  "Thanisandra",
  "Thanisandra Main Road",
  "Thanisandra Main Road,",
  "Tharabanahalli",
  "Thigalarapalya",
  "Thippasandra",
  "Thirumalashettyhally",
  "Thirumenahalli",
  "Thirupalya",
  "Thomas Town",
  "Thubarahalli",
  "Thyagaraja Nagar",
  "Thyagraj Nagar",
  "Tigalarpalya",
  "Tindlu",
  "Tippenahalli",
  "Tirumanahalli",
  "Tr Mill Road, Chamarajpet",
  "Tumkur Road",
  "Tunganagara",
  "Uday Nagar",
  "Udaya Nagar",
  "Udayagiri",
  "Udayapur Village",
  "Ullal Road",
  "Ullal Uppanagar",
  "Ulsoor",
  "Upadhyaya Layout",
  "Upkar Layout",
  "Uttarahalli",
  "Uvce Layout",
  "V.V Puram",
  "Vadarpalya",
  "Vaderahalli",
  "Vaishnavi Layout",
  "Vajarahalli",
  "Varanasi",
  "Varsova Layout",
  "Varthur",
  "Varthur Road",
  "Varthur Road,",
  "Vasantapura Main Road",
  "Vasanth Nagar",
  "Vasantha Vallabha Nagar",
  "Vasanthapura",
  "Vasanthpura",
  "Vasatha Vallbha Nagar",
  "Vayunandana Layout",
  "Veer Sandra",
  "Veerabhadra Nagar",
  "Veerannapalya",
  "Veersandra",
  "Venkatadri Layout",
  "Venkatapura",
  "Venkateshpuram",
  "Venkateswara Nagar",
  "Venugopal Reddy Layout",
  "Versova Layout",
  "Vgp Layout",
  "Vhbcs Layout",
  "Vibhutipura Extension",
  "Vibuthipura",
  "Victoria Layout",
  "Vidhyanagar Cross",
  "Vidya Nagar",
  "Vidyaranyapura",
  "Vignana Nagar",
  "Vijay Nagar",
  "Vijaya Bank Colony",
  "Vijaya Bank Layout",
  "Vijayabank Bank Layout",
  "Vijayanagar",
  "Vijaypura",
  "Vijinapura",
  "Vikram Nagar",
  "Vimanapura",
  "Vinayak Nagar",
  "Vinayaka Layout",
  "Vinayaka Nagar",
  "Virat Nagar",
  "Virgonagar",
  "Virudhu Nagar",
  "Virupakshapura",
  "Vishveshwarya Layout",
  "Vishwanatha Nagenahalli",
  "Vishwapriya Layout",
  "Vishwapriya Nagar",
  "Viswajit Layout",
  "Viswapriyanagar.Begur Road.Bommanahalli.",
  "Vittal Mallya Road",
  "Vittal Nagar",
  "Vittasandra",
  "Vivek Nagar",
  "Viviani Road",
  "Volagerekallahalli",
  "Vyalikaval",
  "Wajid Layout Thanisandra",
  "Weavers Colony",
  "West Of Chord Road",
  "Wheelers Road",
  "Whietfield,",
  "Whitefield",
  "Whitefield Ecc Road",
  "Whitefield,",
  "Williams Town",
  "Wilson Garden",
  "Xavier Layout",
  "Yarandahalli",
  "Yelachenahalli",
  "Yelahanka",
  "Yelahanka New Town",
  "Yelahanka,Mvit College",
  "Yelenahalli",
  "Yemlur",
  "Yemlur, Old Airport Road,",
  "Yeshwanthpur",
  "Yeshwanthpur Industrial Suburb",
  "Zuzuvadi"
];

export default locations;